// Code generated by the proof-kernel-boundary semantic projection; DO NOT EDIT.
// This package is untrusted by design. It forwards observations to the trusted
// kernel and cannot replace the kernel's verdict or policy.
package evaluator

import "github.com/kimjooyoon/gooo-proof-kernel-boundary/internal/kernel"

func Evaluate(input kernel.Input) kernel.Verdict {
	return kernel.Verify(input)
}
